#!/bin/bash
#script for taking backup to  LAP  (livecd_world and current working)

echo "starting sync to  LAP................................................................."
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo "sync LiveCD_World"

rsync -azv /opt/LiveCD_World/ root@192.168.1.102:/opt/LiveCD_World/

echo "LiveCD_World sync Complited"

echo "---------------------------------------------------------------------------------------------"


echo "Start Sync Current Working "

rsync -azv /media/HDD\ 500/Current_Working/ root@192.168.1.102:/media/HDD-180/Current_Working/

echo "Current Working Sync Complited"

echo "Sync Complitted"
