#!/bin/bash
#script for taking livecd backup from opt



	#sudo chmod -R 777 /media/HDD\ 1/vyoma-backups/ISO_BACKUPS/*
	sudo rm -rf  /media/HDD\ 1/vyoma-backups/ISO_BACKUPS/*
	echo "old backup deleted from ISO_BACKUP..................!"
	THISDATE=`date +%d-%m-%Y`
	THISTIME=`date +%H:%M:%S`
	LABEL="LiveCD-Backup"

	#PATH="/opt/LiveCD_World/ISO_BACKUPS"
	DIR_NAME=$LABEL"("${THISDATE}"|"${THISTIME}")"
	mkdir -p /media/HDD\ 1/vyoma-backups/ISO_BACKUPS/${DIR_NAME}
	
	#DIRECTORY created with the current date

if [ -d /media/HDD\ 1/vyoma-backups/ISO_BACKUPS/${DIR_NAME} ]
then
    echo "Backup process started...this will take some time ! you can go for a Coffee!..."
    echo "Copying LiveCD_World -> ISO_BACKUPS...................................." 
    cp -Rav /opt/LiveCD_World/* /media/HDD\ 1/vyoma-backups/ISO_BACKUPS/LiveCD-Backup*
    echo "....................................................All the files copied"
    echo "***********************************************************************"
    echo "Next step backup started (copy from ISO_BACKUP -> LiveCd Server)"
    cp -Rav /media/HDD\ 1/vyoma-backups/ISO_BACKUPS/LiveCD-Backup* /media/HDD\ 500/Vyoma-Backup/Vyoma-Development-Backup/LiveCd-Server/
    
    echo "Step two Backup Complited..............................................."
    echo "Backup Process Sucessfully Complited"
    du -sh /media/HDD\ 1/vyoma-backups/ISO_BACKUPS/${DIR_NAME}
else
    echo "Backup Base folder not found! sorry..."
fi

    echo "-------------------------------------------------------------------------------------------------------------------------------"
    echo "Start Backup of Current Working"
    rsync -av /media/HDD500/Current_Working/ /media/HDD\ 1/vyoma-backups/Current_Working/
    echo "Current Working Backup process Complited !"



